
parameters:
    serius_admin.controller.dashboard.class: Serius\Bundle\AdminBundle\Controller\DashboardController

services:
    # Controllers
    serius_admin.controller.dashboard:
        class: %serius_admin.controller.dashboard.class%